### ISSUE TITLE
Exception when compress css

### ISSUE THREAD

**Issue by dieudv** [alanhamlett/flask-static-compress#4]
When i compress js It's fine but when i try to compress css I got this error:
```
{% compress 'css' %}
	<link rel="stylesheet" type="text/css" href="/static/css/style.css">
{% endcompress %}
```
`
jac.exceptions.InvalidCompressorError
jac.exceptions.InvalidCompressorError: LessCompressor encountered an error when executing lessc: [WinError 2] The system cannot find the file specified Make sure lessc is in your PATH.
`
```
Traceback (most recent call last)
File "e:\proj\nag\venv\lib\site-packages\flask\app.py", line 2309, in __call__
return self.wsgi_app(environ, start_response)
File "e:\proj\nag\venv\lib\site-packages\flask\app.py", line 2295, in wsgi_app
response = self.handle_exception(e)
File "e:\proj\nag\venv\lib\site-packages\flask_restful\__init__.py", line 273, in error_router
return original_handler(e)
File "e:\proj\nag\venv\lib\site-packages\flask\app.py", line 1741, in handle_exception
reraise(exc_type, exc_value, tb)
File "e:\proj\nag\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
raise value
File "e:\proj\nag\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
response = self.full_dispatch_request()
File "e:\proj\nag\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
rv = self.handle_user_exception(e)
File "e:\proj\nag\venv\lib\site-packages\flask_restful\__init__.py", line 273, in error_router
return original_handler(e)
File "e:\proj\nag\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "e:\proj\nag\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
raise value
File "e:\proj\nag\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
rv = self.dispatch_request()
File "e:\proj\nag\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "E:\proj\nag\flaskr\controller\home.py", line 20, in index
return render_template('index.html')
File "e:\proj\nag\venv\lib\site-packages\flask\templating.py", line 135, in render_template
context, ctx.app)
File "e:\proj\nag\venv\lib\site-packages\flask\templating.py", line 117, in _render
rv = template.render(context)
File "e:\proj\nag\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
return original_render(self, *args, **kwargs)
File "e:\proj\nag\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
return self.environment.handle_exception(exc_info, True)
File "e:\proj\nag\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
reraise(exc_type, exc_value, tb)
File "e:\proj\nag\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
raise value.with_traceback(tb)
File "E:\proj\nag\flaskr\templates\index.html", line 1, in top-level template code
{% extends 'base.html' %}
File "E:\proj\nag\flaskr\templates\base.html", line 13, in top-level template code
{% compress 'css' %}
File "e:\proj\nag\venv\lib\site-packages\jac\extension.py", line 39, in _compress_block
return self.compressor.compress(html, compression_type)
File "e:\proj\nag\venv\lib\site-packages\jac\base.py", line 110, in compress
debug=self.config.compressor_debug)
File "e:\proj\nag\venv\lib\site-packages\jac\compressors\less.py", line 60, in compile
Open an interactive python shell in this frameraise InvalidCompressorError(msg)
```

**Comment by alanhamlett** [comment]
What's the output of `pip freeze | grep jac` or what's the version of jac you're using?

**Comment by dieudv** [comment]
I fixed it.
add `shell=True` to this line in ..\jac\compressors\less.py
```
            handler = subprocess.Popen(args,
                                       stdout=subprocess.PIPE,
                                       stdin=subprocess.PIPE,
                                       stderr=subprocess.PIPE, cwd=None, shell=True)
```

**Comment by dieudv** [comment]
i'm using jac==0.17.1
